動作確認でエラー
セクション：SpringBootコース/データ操作をカスタムする/簡単なCRUDの実装/02新規登録
事象：ブラウザでエラー（Internal Server Error, status=500).）が返される
詳細：
1, ブラウザで「http://localhost:8080/course/list」を実行
2, コース名入力後、送信ボタンをクリック
3, Whitelabel Error Page

コンソールでのエラー：
### The error may exist in com/example/mapper/CourseMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: INSERT INTO COURSES (ID, NAME) VALUES (nextval('course_id_seq'), ?)              
### Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near " "
  位置: 80
; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near " "
  位置: 80] with root cause

org.postgresql.util.PSQLException: ERROR: syntax error at or near " "
  位置: 80